In [1]:
# If you want to use a package, import it firstly.
import numpy as np

# 1. Create array/matrix

In [2]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1.shape)
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)
print(type(arr1))

[1 2 3 4 5]
(5,)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
<class 'numpy.ndarray'>


### The type of the array can also be explicitly specified at creation time.

In [3]:
arr1 = np.array([1,2,3,4,5], dtype=float)
print(arr1)
print(arr1.dtype)

[1. 2. 3. 4. 5.]
float64


### Create an array only giving its shape.

In [4]:
print(np.zeros((3)))
print(np.ones((2,5)))
print(np.empty((10,3)))

[0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[-1.72723371e-077 -1.72723371e-077  2.13213046e-314]
 [ 4.94065646e-323  5.43472210e-323              nan]
 [-8.23052036e+303  1.03281903e-255  2.01746193e-284]
 [ 7.01824197e-141  6.93106092e-310  2.13347688e-314]
 [-1.23483229e-132  6.93106082e-310  6.93106086e-310]
 [ 1.11058471e+047  6.93106092e-310  6.93106092e-310]
 [ 7.46435425e-193  6.93105985e-310  2.13347696e-314]
 [-8.23805070e+079  6.93105657e-310  2.13328957e-314]
 [-4.09264026e-245  6.93106092e-310  2.13347802e-314]
 [-3.95424552e-220  6.93106092e-310  6.93105576e-310]]


### Creating sequences of numbers.

In [5]:
print(np.arange(10, 30, 5)) # step interval: 5
print(np.linspace(10, 30, 4)) # number of elements: 4

[10 15 20 25]
[10.         16.66666667 23.33333333 30.        ]


# 2. Basic Array Operations

### Use reshape to change the "shape" of an array.

In [6]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2 = np.array(([
    [[1,2,3,4,5],[6,7,8,9,10]],
    [[1,2,3,4,5],[6,7,8,9,10]]]))
print(arr1.shape)
print(arr2.shape)

(2, 5)
(2, 2, 5)


In [7]:
print(arr1.reshape((5,2)))
print(arr1.reshape((10)))
print(arr1.reshape((2,-1)))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Arithmetic operation of arrays are straightforward.

In [8]:
a = np.array( [20,30,40,50] )
b = np.ones(4)
print(a)
print(b)

[20 30 40 50]
[1. 1. 1. 1.]


In [9]:
print(a+b)
print(a-b)
np.sin(a)

[21. 31. 41. 51.]
[19. 29. 39. 49.]


array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [10]:
# different with python
print([1,2,3] + [2,3,4])
print(np.array([1,2,3]) + np.array([2,3,4]))
print([1,2,3,4,5] * 3)
print(np.array([1,2,3,4,5]) * 3)

[1, 2, 3, 2, 3, 4]
[3 5 7]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 3  6  9 12 15]


### Aggregate functions can be applied on specific axis.

In [11]:
b = np.arange(12).reshape(3,4)
print(b)
print(b.sum())
print(b.sum(axis=0)) #aggregate across the rows
print(b.sum(axis=1)) #aggregate across the columns

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]


### Broadcasting
When operands with numpy function involved do not have exactly the same shape. Numpy tries to boardcast one of the operands to make the sizes of all arrays match, so elementwise operations can be performed.

Rule 1: If all input arrays do not have the same number of dimensions, a “1” will be repeatedly prepended to the shapes of the smaller arrays until all the arrays have the same number of dimensions.

Rule 2: Arrays with a size of 1 along a particular dimension is expanded(duplicated) to the largest size along that dimension across operands.

In [12]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
print(a * b)

[2. 4. 6.]


In [13]:
a = np.array([0.0, 10.0, 20.0, 30.0]).reshape(4,-1)
b = np.array([1.0, 2.0, 3.0])
print(a)
print(b)
print(a+b)

[[ 0.]
 [10.]
 [20.]
 [30.]]
[1. 2. 3.]
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


# 3. Indexing, Slicing, Stacking and Iterating

### Indexing

In [14]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
print(a[0,2])
print(a[1])
print(a[0,-1])

2
[4 5 6 7]
3


### Slicing

In [16]:
print(a[0:2, :])
print(a[:, 0:2])

[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [4 5]
 [8 9]]


More fancy indexing and index tricks can be found in Numpy Tutorial: https://numpy.org/devdocs/user/quickstart.html

### Stacking

In [17]:
a = np.array([[ 8.,  8.],
       [ 0.,  0.]])
b = np.array([[ 1.,  8.],
       [ 0.,  4.]])
print(np.vstack((a,b))) #vertically
print(np.hstack((a,b))) #horizontally

[[8. 8.]
 [0. 0.]
 [1. 8.]
 [0. 4.]]
[[8. 8. 1. 8.]
 [0. 0. 0. 4.]]


### Iterating

In [18]:
for row in a:
    print(row)

[8. 8.]
[0. 0.]


In [19]:
for row in a:
    for element in row:
        print(element)

8.0
8.0
0.0
0.0


In [20]:
for element in a.flat:
    print(element)

8.0
8.0
0.0
0.0


Python comprehension (A trick to generate your list)