In [1]:
# If you want to use a package, import it firstly.
import numpy as np

# 1. Create array/matrix

In [5]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1.shape)
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)
print(type(arr1))

[1 2 3 4 5]
(5,)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
<class 'numpy.ndarray'>


### The type of the array can also be explicitly specified at creation time.

In [6]:
arr1 = np.array([1,2,3,4,5], dtype=float)
print(arr1)
print(arr1.dtype)

[1. 2. 3. 4. 5.]
float64


### Create an array only giving its shape.

In [7]:
print(np.zeros((3)))
print(np.ones((2,5)))
print(np.empty((10,3)))

[0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[9.58793842e-312 9.58487353e-322 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 5.02034658e+175]
 [1.46246086e+165 2.47187544e-056 2.33859237e-052]
 [3.05948319e-057 1.47763641e+248 1.16096346e-028]
 [7.69165785e+218 1.35617292e+248 3.10208759e-032]
 [4.66466189e-033 9.35154620e-067 1.35022226e+161]
 [4.30513416e-096 6.32299154e+233 6.48224638e+170]
 [5.22411352e+257 5.74020278e+180 8.37174974e-144]
 [1.41529402e+161 9.16651763e-072 5.38016474e+097]
 [5.35654387e-038 3.25188199e+126 1.58268989e-319]]


### Creating sequences of numbers.

In [9]:
print(np.arange(10, 30, 5)) # step interval: 5
print(np.linspace(10, 30, 3)) # number of elements: 4

[10 15 20 25]
[10. 20. 30.]


# 2. Array Basic Operations

### Use reshape to change the "shape" of an array.

In [10]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2 = np.array(([
    [[1,2,3,4,5],[6,7,8,9,10]],
    [[1,2,3,4,5],[6,7,8,9,10]]]))
print(arr1.shape)
print(arr2.shape)

(2, 5)
(2, 2, 5)


In [16]:
print(arr1.reshape((5,2)))
print(arr1.reshape((10)))
print(arr1.reshape((2,-1)))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Arithmetic operation of arrays are straightforward.

In [18]:
a = np.array( [20,30,40,50] )
b = np.ones(4)
print(a)
print(b)

[20 30 40 50]
[1. 1. 1. 1.]


In [17]:
print(a+b)
print(a-b)
np.sin(a)

[21. 31. 41. 51.]
[19. 29. 39. 49.]


array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [20]:
[1,2,3] + [2,3,4]

[1, 2, 3, 2, 3, 4]

In [19]:
# elementwise functions are provided by numpy.
# import math
# math.sin(a)

SyntaxError: invalid syntax (<ipython-input-19-4c99313bb405>, line 1)

In [21]:
# different with python
print([1,2,3,4,5] * 3)
print(np.array([1,2,3,4,5]) * 3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 3  6  9 12 15]


### Aggregate functions can be applied on specific axis.

In [22]:
b = np.arange(12).reshape(3,4)
print(b)
print(b.sum())
print(b.sum(axis=0)) #aggregate across the rows
print(b.sum(axis=1)) #aggregate across the columns

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]


### Broadcasting
When operands with numpy function involved do not have exactly the same shape. Numpy tries to boardcast one of the operands to make the sizes of all arrays match, so elementwise operations can be performed.

Rule 1: If all input arrays do not have the same number of dimensions, a “1” will be repeatedly prepended to the shapes of the smaller arrays until all the arrays have the same number of dimensions.

Rule 2: Arrays with a size of 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension, by expanding the value along that dimension.

In [23]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
print(a * b)

[2. 4. 6.]


In [24]:
a = np.array([0.0, 10.0, 20.0, 30.0]).reshape(4,-1)
b = np.array([1.0, 2.0, 3.0])
print(a)
print(b)
print(a+b)

[[ 0.]
 [10.]
 [20.]
 [30.]]
[1. 2. 3.]
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


# 3. Indexing, Slicing, Stacking and Iterating

### Indexing

In [25]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [29]:
print(a[0,2])
print(a[-1,-1])
print(a[0:2])

2
11
[[0 1 2 3]
 [4 5 6 7]]


### Slicing

In [30]:
print(a[1,1])
print(a[0:2, 0:2])
print(a[0:2, :])
print(a[:, 0:2])

5
[[0 1]
 [4 5]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [4 5]
 [8 9]]


More fancy indexing and index tricks can be found in Numpy Tutorial: https://numpy.org/devdocs/user/quickstart.html

### Stacking

In [31]:
a = np.array([[ 8.,  8.],
       [ 0.,  0.]])
b = np.array([[ 1.,  8.],
       [ 0.,  4.]])
print(np.vstack((a,b))) #vertically
print(np.hstack((a,b))) #horizontally

[[8. 8.]
 [0. 0.]
 [1. 8.]
 [0. 4.]]
[[8. 8. 1. 8.]
 [0. 0. 0. 4.]]


### Iterating

In [33]:
for row in a:
    for element in row:
        print(element)

8.0
8.0
0.0
0.0


In [ ]:
for element in a.flat:
    print(element)

Python comprehension (A trick to generate your list)

In [ ]:
print([element for element in a.flat])