In [1]:
%matplotlib inline

In [2]:
import torch
import numpy as np

In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


**From a NumPy array**

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [6]:
x_data.dtype

torch.int64

**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [7]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6474, 0.8724],
        [0.1481, 0.4385]]) 



**With random or constant values:**

``shape`` is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.



In [10]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)



print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7657, 0.2986, 0.1623],
        [0.0786, 0.7390, 0.1736]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### Attributes of a Tensor


In [9]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

n = tensor.numpy()
print(f"numpy: {n}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
numpy: [[0.46625715 0.22385132 0.31584692 0.01633811]
 [0.45380384 0.8143385  0.41285163 0.7822639 ]
 [0.00604796 0.4389813  0.67630404 0.7410824 ]]


#### Operations on Tensors
~~~~~~~~~~~~~~~~~

By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using
``.to`` method (after checking for GPU availability). Keep in mind that copying large tensors
across devices can be expensive in terms of time and memory!



In [ ]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

**Standard numpy-like indexing and slicing:**



In [11]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


stack: Concatenates sequence of tensors along a new dimension.

cat: Concatenates sequence of tensors along  the given dimension.

In [12]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1.shape)

torch.Size([4, 12])


In [13]:
t2 = torch.stack([tensor, tensor, tensor], dim=1)
print(t2.shape)

torch.Size([4, 3, 4])


**Arithmetic operations**



In [14]:
tensor = torch.tensor([[1,2,3], [1,2,3]])

# This computes the element-wise addition.
z1 = tensor + tensor
z2 = tensor.add(tensor)
z3 = torch.add(tensor, tensor)
print(z1)


# This computes the element-wise product.
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.mul(tensor, tensor)
print(z1)

tensor([[2, 4, 6],
        [2, 4, 6]])
tensor([[1, 4, 9],
        [1, 4, 9]])


In [15]:
tensor = torch.tensor([[1,2,3], [1,2,3]])

# This computes the matrix multiplication between two tensors.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.matmul(tensor, tensor.T)
y4 = torch.mm(tensor, tensor.T)
print(y1)


tensor([[14, 14],
        [14, 14]])


The 'out' argument can be used to put the result into a exising tensor.

In [ ]:
print(f"{tensor} \n")
torch.add(tensor, 5, out=tensor)
print(tensor)

Use item() to get the raw value from a pytorch tensor.



In [16]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12 <class 'int'>


### Automatic Differentiation
To compute those gradients, PyTorch has a built-in differentiation engine called torch.autograd. It supports automatic computation of gradient for any computational graph.

In [18]:
import torch

x = torch.tensor([1.])  # input tensor
y = torch.tensor([2.])  # expected output
w = torch.tensor([1.], requires_grad=True)
b = torch.tensor([0.], requires_grad=True)
z = x*w+b
loss = torch.square(z - y).sum()

To compute those derivatives, we call
``loss.backward()``, and then retrieve the values from ``w.grad`` and
``b.grad`` to get the derivatives $\frac{\partial loss}{\partial w}$ and
$\frac{\partial loss}{\partial b}$.


In [19]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([-2.])
tensor([-2.])
